config/routes.rb
Rails.application.routes.draw do
  
  get 'orders/index'
  get 'orders/show/:id', to: 'orders#show', as: 'order'
  get 'orders/create'
  get 'orders/po'
  post 'orders/create'
  get 'orders/new'
  resources :pos, :controller => 'orders'
  resources :locations

  get 'products/new'

  get 'products/create'
  post 'products/create'

  get 'products/update'

  get 'products/edit'

  get 'products/destroy'

  get 'products/index'

  get 'products/show/:id', to: 'products#show', as: 'product'

  get 'companies/index'

  get 'companies/create'

  get 'companies/show'

  get 'companies/destroy'

  devise_for :users
  root 'pages#index'
  get 'pages/index'

  get 'pages/about'

  get 'pages/services'

  get 'pages/contact'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :locations
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :products
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :company
  has_one :inventory
  has_many :products, through: :inventory
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_one :product
  belongs_to :po
  validates :product_id, presence: true, numericality: true
  validates :quantity, presence: true, numericality: true

  def my_product(product_id)
    @my_product = Product.where(id: product_id)
    @my_product[0].name
  end

  def my_product_classification(product_id)
    @my_product = Product.where(id: product_id)
    @my_product[0].classification
  end
end

app/models/po.rb
class Po < ActiveRecord::Base
  has_one :supplier
  has_many :orders
  accepts_nested_attributes_for :orders, :allow_destroy => true
  
  def my_supplier(supplier)
    my_supplier = Supplier.where(id: supplier)
    my_supplier[0].name 
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :order
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  belongs_to :po
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :company
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
before_action :authenticate_user!
  def index
  end

  def create
  end

  def show
  end

  def destroy
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.where(current_user.company)
    end
  end

  def new
    @location = Location.new
  end

  def create
    @company = Company.find_by current_user.company_id
    if @company.nil?
      @company.company_id = 1
    end

    @location = Location.new(location_params)  
    
    if @location.save
      @location.update_column(:company_id, @company)
      redirect_to root_url
    else
      redirect_to locations_path
    end
  end

  def update
  end

  def destroy
  end

  def show
    if params[:search].present?
      @location = Location.find(params[:search])  
    else
      
      @location = Location.find(params[:id])
    end
  end

  private
  def location_params
    params.require(:location).permit(:address)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @po = Po.new
  end
  def create
    @po = Po.new(order_params)
    #binding.pry
    if @po.save
      redirect_to root_url
    else
      redirect_to products_index_path 
    end
  end
  def show
    @order = Order.find(params[:id])
  end
  def po
    @pos = Po.all
  end
  private
  def order_params
    params.require(:po).permit(:supplier_id, orders_attributes: [:product_id, :quantity])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    #binding.pry
    if @product.save
      redirect_to root_url
    else
      redirect_to products_index_path 
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
  private
  def product_params
    params.require(:product).permit(:name, :stocknum, :classification)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/layouts/_neworder.html.erb
<div class='ui segment'> 
<%= @product.id %> | <%= @product.name %>
<%= form_for @order do |f| %>
  Item: <%= f.text_field :product_id, :placeholder => @product.id %><br>
  Quantity: <%= f.text_field :quantity %><br>
  <div class='orderup'>
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Item Shoppe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <%= render 'pages/navbar.html.erb' %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/_navbar.html.erb
<div class='initial_header'>
  <div class='ui icon button mini yoshi'>
   <%= semantic_icon('cloud') %>
 </div>
 <div class='logo'>ItemShoppe</div>

 <div class='smedia logo'><%= semantic_icon('facebook basic') %></div>
 <div class='smedia logo'><%= semantic_icon('twitter basic') %></div>
 <div class='smedia logo logoutButton'>
  <% if current_user %> 
  <%= link_to destroy_user_session_path, :method => :delete do %>
  <%= semantic_icon('remove sign') %>
  <% end %>
  <%= current_user.email %>
  <% end %>
</div>
</div>

<div class="ui red vertical demo sidebar menu">
  <div class="item" id='login'>
    <%= semantic_icon('cloud') %>
    <%= link_to("Log In", root_url) %>
  </div>
  <div class="item" id='locations_list'>
    <%= semantic_icon('flag') %>
    <%= link_to("Stores/Locations", locations_path) %>
  </div>
  <div class="item" id='products_list'>
    <%= semantic_icon('barcode') %>
    <%= link_to("Products/Inventory", products_index_path) %>
  </div>
  <div class='item'>
  <p class='pretitle'>Purchase Orders</p><br>
  <div class='menu'>
    <div class="item" id='place_single_order'>
      <%= semantic_icon('table') %>
      <%= link_to("Place Single Order", orders_new_path) %>
    </div>
    <div class="item" id='all_pos'>
      <%= semantic_icon('cart') %>
      <%= link_to("All PO's", orders_po_path) %>
    </div>
    </div>
  </div>
</div>


<div class="ui small modal">
  <%= render 'orders/order' %>
</div>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<br><br>
<div class='ui divided grid'>
  <div class='row'>
    <% if !current_user %>
      <%= link_to new_user_session_path do %>
        <%= semantic_icon('key') %> Login
       <% end %>
    <% else %>
    <div class='four wide column ui segment'>
      <%= link_to products_index_path do %>
      <div class='ui button blue' id='barcode'>
        <%= semantic_icon('barcode') %>
      </div>
      <% end %>
      <%= link_to locations_path do %>
      <div class='ui button blue' id='flag'>  
        <%= semantic_icon('flag') %>
      </div> 
      <% end %>
      <%= link_to pos_path do %>
      <div class='ui button blue' id='cart'>
        <%= semantic_icon('shopping cart') %>
      </div>
      <% end %>
      <% end %>
    </div>
    <div class='four wide column floated left ui info message blue stackable'>
    Welcome to ItemShoppe: inventory management across shops!
    </div>
    <div class='four wide column floated right ui infor message green stackable'>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
    <div class='four wide column floated right ui infor message green stackable'>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
  </div>
</div>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>