config/routes.rb
Rails.application.routes.draw do
  
  get 'orders/index'
  get 'orders/show/:id', to: 'orders#show', as: 'order'
  get 'orders/create'
  get 'orders/po'
  post 'orders/create'
  get 'orders/new'
  resources :pos, :controller => 'orders'
  resources :locations

  get 'products/new'

  get 'products/create'
  post 'products/create'

  get 'products/update'

  get 'products/edit'

  get 'products/destroy'

  get 'products/index'

  get 'products/show/:id', to: 'products#show', as: 'product'

  get 'companies/index'

  get 'companies/create'

  get 'companies/show'

  get 'companies/destroy'

  devise_for :users
  root 'pages#index'
  get 'pages/index'

  get 'pages/about'

  get 'pages/services'

  get 'pages/contact'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :locations
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :products
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :company
  has_one :inventory
  has_many :products, through: :inventory
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_one :product
  belongs_to :po
  validates :product_id, presence: true, numericality: true
  validates :quantity, presence: true, numericality: true

  def my_product(product_id)
    @my_product = Product.where(id: product_id)
    @my_product[0].name
  end

  def my_product_classification(product_id)
    @my_product = Product.where(id: product_id)
    @my_product[0].classification
  end
end

app/models/po.rb
class Po < ActiveRecord::Base
  has_one :supplier
  has_many :orders
  accepts_nested_attributes_for :orders, :allow_destroy => true
  
  def my_supplier(supplier)
    my_supplier = Supplier.where(id: supplier)
    my_supplier[0].name 
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :order
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  belongs_to :po
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :company
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
before_action :authenticate_user!
  def index
  end

  def create
  end

  def show
  end

  def destroy
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:search].present?
      @locations = Location.near(params[:search], 50, :order => :distance)
    else
      @locations = Location.where(current_user.company)
    end
  end

  def new
    @location = Location.new
  end

  def create
    @company = Company.find_by current_user.company_id
    if @company.nil?
      @company.company_id = 1
    end

    @location = Location.new(location_params)  
    
    if @location.save
      @location.update_column(:company_id, @company)
      redirect_to root_url
    else
      redirect_to locations_path
    end
  end

  def update
  end

  def destroy
  end

  def show
    if params[:search].present?
      @location = Location.find(params[:search])  
    else
      
      @location = Location.find(params[:id])
    end
  end

  private
  def location_params
    params.require(:location).permit(:address)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @po = Po.new
  end
  def create
    @po = Po.new(order_params)
    #binding.pry
    if @po.save
      redirect_to root_url
    else
      redirect_to products_index_path 
    end
  end
  def show
    @order = Order.find(params[:id])
  end
  def po
    @pos = Po.all
  end
  private
  def order_params
    params.require(:po).permit(:supplier_id, orders_attributes: [:product_id, :quantity])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    #binding.pry
    if @product.save
      redirect_to root_url
    else
      redirect_to products_index_path 
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
  private
  def product_params
    params.require(:product).permit(:name, :stocknum, :classification)
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/destroy.html.erb
<h1>Companies#destroy</h1>
<p>Find me in app/views/companies/destroy.html.erb</p>

app/views/companies/index.html.erb
<div class='ui button mini'><%= semantic_icon('archive') %> <p class='whisper'>All Items</p>
</div>

app/views/companies/show.html.erb
<h1>Companies#show</h1>
<p>Find me in app/views/companies/show.html.erb</p>

app/views/locations/destroy.html.erb
<h1>Locations#destroy</h1>
<p>Find me in app/views/locations/destroy.html.erb</p>

app/views/locations/index.html.erb
<h1 class='title'>Locations#index</h1>
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search near", :name => nil %>
  </p>
<% end %>
<%= link_to new_location_path do %>
<div class='ui mini button teal'>
	<%= semantic_icon(:building) %>
  New
</div>
<% end %>
<div class='ui segment'>
<% @locations.each do |location| %>
	<div class='ui mini button blue'>
  <%= link_to location_path(location) do %>
  <%= semantic_icon(:briefcase) %>Details
  </div>
  <% end %>
  <div class='location' id='<%= location.id %>'><%= location.address %></div><br><br>
<% end %>
</div>

app/views/locations/new.html.erb
<br><br>
<h1 class='title'>Add a new location</h1>

<div class='ui form'>
  <%= form_for ([@company, @location]), url: locations_create_path do |f| %>
  <%= f.label :address %>:
  <%= f.text_field :address %><br />  
  <%= f.submit %>
  <% end %>
</div>

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>
<ul>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>

app/views/orders/_order.html.erb
<br><br>
<div class='ui segment'>
  Added to shopping cart!
  <div class='ui button mini floated right OK'>
    ok!
  </div>
</div>

app/views/orders/create.html.erb
<%= render 'order' %>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<%= link_to products_index_path do %>
<div class='ui button mini allItems'>
  All Items
</div>
<% end %>


<% @orders.each do |order| %>
<div class='ui segment allOrders'>
<%= link_to order_path(order), class: 'orderId', id: order.id do %> 
  Order id: <%= order.id %><br>
  <% end %>
  Order quantity: <%= order.quantity %><br>
  Product id: <%= order.product_id %><br>
  pid: <%= order.product_id %><br>
  Product: <%= order.my_product(order.product_id) %><br>
  Quantity: <%= order.quantity %><br>
</div>
<% end %>

app/views/orders/new.html.erb
<br><br>
<div class='ui segment'>
  <div class='title'>Create a Purchase Order</div>
  <%= nested_form_for @po do |f| %>
  <%= f.label 'Supplier id:' %>
  <%= f.text_field :supplier_id %>
  <%= f.fields_for :orders do |order_form| %>
  Product id: <%= order_form.text_field :product_id %><br>
  Quantity: <%= order_form.text_field :quantity %>
  <% end %>
  <div class='colorme'>
    <p class='bold'><%= f.link_to_add "Add an order", :orders %></p>
  </div>
    <%= f.submit 'Save PO' %>
  <% end %>
</div>

app/views/orders/po.html.erb
<br><br>
<% @pos.each do |po| %>
<div class='ui message'>
  <div class='header'>
    Purchase Order # <%= po.id %>
  </div> 
  Supplier: <%= po.my_supplier(po.supplier_id) %><br>
  <div class='ui header'>
    Product(s):
  </div> 
  <% po.orders.each do |order| %>
  <div class='ui segment teal'>
    Name: <%= order.my_product(order.product_id) %><br>
    Classification: <%= order.my_product_classification(order.product_id) %><br>
    Quantity: <%= order.quantity %><br>
    <div class='ui divider horizontal icon'>
      <%= semantic_icon('level down') %>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/orders/show.html.erb
My order id is: <%= @order.product_id %> <br>
I ordered: 
 <%= @order.quantity %>

app/views/products/_product.html.erb
<% @products.each do |product| %>
<div class='ui segment product_instance'>
  <%= link_to product_path(product) do %>
  <div data-id="<%= product.id %>" class='orderUp ui teal button mini' title='Add 1 unit to wish list'>
   <%= semantic_icon('text file') %>
 </div>
 <% end %>
 <%= product.name %> : 
 <%= product.classification %>
<div class='ui vertical divider'></div>
<div class='lesser_details'>
  ID number: <%= product.id %>
</div>
</div>
<% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<br><br>

<div class='title'>
  <%= link_to products_new_path do %>
  <div class='ui mini button blue newProduct'>
    <%= semantic_icon(:add) %> New
  </div>
  <% end %>
  List of all products:
</div> 
<%= render 'product' %>

app/views/products/new.html.erb
<h1 class='title'>Products#new</h1>
<div class='ui segment'>
<div class='ui form'>
<%= form_for @product, url: products_create_path do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />
  <%= f.label :classification %>:
  <%= f.text_field :classification %><br />
  <%= f.label :stocknum %>:
  <%= f.text_field :stocknum %><br />
  <%= f.submit class: 'ui green mini button' %>
  <% end %>
  </div>
  </div>

app/views/products/order_list.html.erb
<br><br>
<div class='ui segment'>
	lol
</div>

app/views/products/show.html.erb
<h1>Products#show</h1>
<div class='appendme'>
<%= @product.name %>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>